#include "swapchain.hpp"
#include "config.hpp"
#include "keybinds.hpp"
#include "logger.hpp"

#include <cstring>
#include <mutex>
#include <unordered_map>

// generated by meson via glslangValidator --vn, dont edit
#include "fullscreen_vert.h"
#include "color_frag.h"

namespace vksumi
{
    namespace
    {
        std::mutex                                                                   g_lock;
        std::unordered_map<void*,        DeviceState>                                g_devices;
        std::unordered_map<VkSwapchainKHR, std::shared_ptr<SwapchainState>>          g_swapchains;

        template<typename T>
        void* keyOf(T h) { return *reinterpret_cast<void**>(h); }

        uint32_t findMemoryType(const VkPhysicalDeviceMemoryProperties& mp,
                                uint32_t                                typeBits,
                                VkMemoryPropertyFlags                   required)
        {
            for (uint32_t i = 0; i < mp.memoryTypeCount; ++i)
            {
                if ((typeBits & (1u << i)) &&
                    (mp.memoryTypes[i].propertyFlags & required) == required)
                    return i;
            }
            return UINT32_MAX;
        }

        void barrier(const DeviceDispatch& vkd,
                     VkCommandBuffer       cb,
                     VkImage               image,
                     VkImageLayout         oldLayout,
                     VkImageLayout         newLayout,
                     VkAccessFlags         srcAccess,
                     VkAccessFlags         dstAccess,
                     VkPipelineStageFlags  srcStage,
                     VkPipelineStageFlags  dstStage)
        {
            VkImageMemoryBarrier b{};
            b.sType                       = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
            b.oldLayout                   = oldLayout;
            b.newLayout                   = newLayout;
            b.srcAccessMask               = srcAccess;
            b.dstAccessMask               = dstAccess;
            b.srcQueueFamilyIndex         = VK_QUEUE_FAMILY_IGNORED;
            b.dstQueueFamilyIndex         = VK_QUEUE_FAMILY_IGNORED;
            b.image                       = image;
            b.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
            b.subresourceRange.levelCount = 1;
            b.subresourceRange.layerCount = 1;
            vkd.CmdPipelineBarrier(cb, srcStage, dstStage, 0, 0, nullptr, 0, nullptr, 1, &b);
        }
    } // anon

    void registerDevice(VkDevice d, DeviceState s)
    {
        std::lock_guard<std::mutex> l(g_lock);
        g_devices[keyOf(d)] = s;
    }
    DeviceState* findDevice(VkDevice d)
    {
        std::lock_guard<std::mutex> l(g_lock);
        auto it = g_devices.find(keyOf(d));
        return it == g_devices.end() ? nullptr : &it->second;
    }
    DeviceState* findDeviceByQueue(VkQueue q)
    {
        std::lock_guard<std::mutex> l(g_lock);
        auto it = g_devices.find(keyOf(q));
        return it == g_devices.end() ? nullptr : &it->second;
    }
    void unregisterDevice(VkDevice d)
    {
        std::lock_guard<std::mutex> l(g_lock);
        g_devices.erase(keyOf(d));
    }

    void registerSwapchain(VkSwapchainKHR sc, std::shared_ptr<SwapchainState> st)
    {
        std::lock_guard<std::mutex> l(g_lock);
        g_swapchains[sc] = std::move(st);
    }
    std::shared_ptr<SwapchainState> findSwapchain(VkSwapchainKHR sc)
    {
        std::lock_guard<std::mutex> l(g_lock);
        auto it = g_swapchains.find(sc);
        return it == g_swapchains.end() ? nullptr : it->second;
    }
    void unregisterSwapchain(VkSwapchainKHR sc)
    {
        std::lock_guard<std::mutex> l(g_lock);
        g_swapchains.erase(sc);
    }

    SwapchainState::SwapchainState(const DeviceState& dev, VkSwapchainKHR sc, VkExtent2D extent, VkFormat fmt)
        : m_dev(dev), m_realSwapchain(sc), m_extent(extent), m_format(fmt)
    {}

    SwapchainState::~SwapchainState()
    {
        const auto& vkd = m_dev.vkd;
        vkd.DeviceWaitIdle(m_dev.device);

        for (auto f  : m_inFlight)     if (f)  vkd.DestroyFence(m_dev.device, f, nullptr);
        for (auto s  : m_renderDone)   if (s)  vkd.DestroySemaphore(m_dev.device, s, nullptr);
        if (m_cmdPool)                 vkd.DestroyCommandPool(m_dev.device, m_cmdPool, nullptr);
        if (m_pipeline)                vkd.DestroyPipeline(m_dev.device, m_pipeline, nullptr);
        if (m_frag)                    vkd.DestroyShaderModule(m_dev.device, m_frag, nullptr);
        if (m_vert)                    vkd.DestroyShaderModule(m_dev.device, m_vert, nullptr);
        if (m_pipeLayout)              vkd.DestroyPipelineLayout(m_dev.device, m_pipeLayout, nullptr);
        if (m_dsPool)                  vkd.DestroyDescriptorPool(m_dev.device, m_dsPool, nullptr);
        if (m_dsLayout)                vkd.DestroyDescriptorSetLayout(m_dev.device, m_dsLayout, nullptr);
        if (m_renderPass)              vkd.DestroyRenderPass(m_dev.device, m_renderPass, nullptr);
        if (m_sampler)                 vkd.DestroySampler(m_dev.device, m_sampler, nullptr);

        for (auto fb : m_framebuffers) if (fb) vkd.DestroyFramebuffer(m_dev.device, fb, nullptr);
        for (auto v  : m_realViews)    if (v)  vkd.DestroyImageView(m_dev.device, v, nullptr);
        for (auto v  : m_fakeViews)    if (v)  vkd.DestroyImageView(m_dev.device, v, nullptr);
        for (auto i  : m_fakeImages)   if (i)  vkd.DestroyImage(m_dev.device, i, nullptr);
        for (auto m  : m_fakeMemory)   if (m)  vkd.FreeMemory(m_dev.device, m, nullptr);
    }

    bool SwapchainState::initImages(const VkSwapchainCreateInfoKHR& createInfo)
    {
        const auto& vkd = m_dev.vkd;

        uint32_t count = 0;
        vkd.GetSwapchainImagesKHR(m_dev.device, m_realSwapchain, &count, nullptr);
        m_realImages.resize(count);
        vkd.GetSwapchainImagesKHR(m_dev.device, m_realSwapchain, &count, m_realImages.data());

        VkPhysicalDeviceMemoryProperties memProps{};
        m_dev.vki.GetPhysicalDeviceMemoryProperties(m_dev.physicalDevice, &memProps);

        m_fakeImages.resize(count, VK_NULL_HANDLE);
        m_fakeMemory.resize(count, VK_NULL_HANDLE);
        m_fakeViews .resize(count, VK_NULL_HANDLE);
        m_realViews .resize(count, VK_NULL_HANDLE);
        m_realFirstUse.assign(count, true);

        for (uint32_t i = 0; i < count; ++i)
        {
            VkImageCreateInfo ic{};
            ic.sType         = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
            ic.imageType     = VK_IMAGE_TYPE_2D;
            ic.format        = m_format;
            ic.extent        = { m_extent.width, m_extent.height, 1 };
            ic.mipLevels     = 1;
            ic.arrayLayers   = createInfo.imageArrayLayers ? createInfo.imageArrayLayers : 1;
            ic.samples       = VK_SAMPLE_COUNT_1_BIT;
            ic.tiling        = VK_IMAGE_TILING_OPTIMAL;
            ic.usage         = createInfo.imageUsage | VK_IMAGE_USAGE_SAMPLED_BIT;
            ic.sharingMode   = VK_SHARING_MODE_EXCLUSIVE;
            ic.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

            if (vkd.CreateImage(m_dev.device, &ic, nullptr, &m_fakeImages[i]) != VK_SUCCESS)
            { VKSUMI_LOG("CreateImage(fake[%u]) failed", i); return false; }

            VkMemoryRequirements mr{};
            vkd.GetImageMemoryRequirements(m_dev.device, m_fakeImages[i], &mr);

            uint32_t mt = findMemoryType(memProps, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
            if (mt == UINT32_MAX) { VKSUMI_LOG("no DEVICE_LOCAL memory type"); return false; }

            VkMemoryAllocateInfo ma{};
            ma.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
            ma.allocationSize  = mr.size;
            ma.memoryTypeIndex = mt;
            if (vkd.AllocateMemory(m_dev.device, &ma, nullptr, &m_fakeMemory[i]) != VK_SUCCESS)
            { VKSUMI_LOG("AllocateMemory(fake[%u]) failed", i); return false; }

            vkd.BindImageMemory(m_dev.device, m_fakeImages[i], m_fakeMemory[i], 0);

            VkImageViewCreateInfo vc{};
            vc.sType                       = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
            vc.viewType                    = VK_IMAGE_VIEW_TYPE_2D;
            vc.format                      = m_format;
            vc.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
            vc.subresourceRange.levelCount = 1;
            vc.subresourceRange.layerCount = 1;

            vc.image = m_fakeImages[i];
            if (vkd.CreateImageView(m_dev.device, &vc, nullptr, &m_fakeViews[i]) != VK_SUCCESS)
            { VKSUMI_LOG("CreateImageView(fake[%u]) failed", i); return false; }

            vc.image = m_realImages[i];
            if (vkd.CreateImageView(m_dev.device, &vc, nullptr, &m_realViews[i]) != VK_SUCCESS)
            { VKSUMI_LOG("CreateImageView(real[%u]) failed", i); return false; }
        }

        return true;
    }

    bool SwapchainState::initSampler()
    {
        VkSamplerCreateInfo s{};
        s.sType        = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
        s.magFilter    = VK_FILTER_NEAREST;
        s.minFilter    = VK_FILTER_NEAREST;
        s.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        s.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        s.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        s.maxLod       = 0.0f;
        return m_dev.vkd.CreateSampler(m_dev.device, &s, nullptr, &m_sampler) == VK_SUCCESS;
    }

    bool SwapchainState::initRenderPass()
    {
        VkAttachmentDescription a{};
        a.format         = m_format;
        a.samples        = VK_SAMPLE_COUNT_1_BIT;
        a.loadOp         = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
        a.storeOp        = VK_ATTACHMENT_STORE_OP_STORE;
        a.stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
        a.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
        a.initialLayout  = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        a.finalLayout    = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

        VkAttachmentReference ref{};
        ref.attachment = 0;
        ref.layout     = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

        VkSubpassDescription sub{};
        sub.pipelineBindPoint    = VK_PIPELINE_BIND_POINT_GRAPHICS;
        sub.colorAttachmentCount = 1;
        sub.pColorAttachments    = &ref;

        VkSubpassDependency dep{};
        dep.srcSubpass    = VK_SUBPASS_EXTERNAL;
        dep.dstSubpass    = 0;
        dep.srcStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        dep.dstStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        dep.srcAccessMask = 0;
        dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

        VkRenderPassCreateInfo r{};
        r.sType           = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
        r.attachmentCount = 1;
        r.pAttachments    = &a;
        r.subpassCount    = 1;
        r.pSubpasses      = &sub;
        r.dependencyCount = 1;
        r.pDependencies   = &dep;

        return m_dev.vkd.CreateRenderPass(m_dev.device, &r, nullptr, &m_renderPass) == VK_SUCCESS;
    }

    bool SwapchainState::initDescriptorLayout()
    {
        VkDescriptorSetLayoutBinding b{};
        b.binding         = 0;
        b.descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        b.descriptorCount = 1;
        b.stageFlags      = VK_SHADER_STAGE_FRAGMENT_BIT;
        b.pImmutableSamplers = &m_sampler;

        VkDescriptorSetLayoutCreateInfo c{};
        c.sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        c.bindingCount = 1;
        c.pBindings    = &b;
        return m_dev.vkd.CreateDescriptorSetLayout(m_dev.device, &c, nullptr, &m_dsLayout) == VK_SUCCESS;
    }

    bool SwapchainState::initPipeline()
    {
        const auto& vkd = m_dev.vkd;

        VkShaderModuleCreateInfo sm{};
        sm.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        sm.codeSize = sizeof(fullscreen_vert);
        sm.pCode    = fullscreen_vert;
        if (vkd.CreateShaderModule(m_dev.device, &sm, nullptr, &m_vert) != VK_SUCCESS) return false;

        sm.codeSize = sizeof(color_frag);
        sm.pCode    = color_frag;
        if (vkd.CreateShaderModule(m_dev.device, &sm, nullptr, &m_frag) != VK_SUCCESS) return false;

        VkPushConstantRange pcr{};
        pcr.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
        pcr.offset     = 0;
        pcr.size       = sizeof(Knobs);

        VkPipelineLayoutCreateInfo pl{};
        pl.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        pl.setLayoutCount         = 1;
        pl.pSetLayouts            = &m_dsLayout;
        pl.pushConstantRangeCount = 1;
        pl.pPushConstantRanges    = &pcr;
        if (vkd.CreatePipelineLayout(m_dev.device, &pl, nullptr, &m_pipeLayout) != VK_SUCCESS) return false;

        VkPipelineShaderStageCreateInfo stages[2]{};
        stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
        stages[0].module = m_vert;
        stages[0].pName  = "main";
        stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
        stages[1].module = m_frag;
        stages[1].pName  = "main";

        VkPipelineVertexInputStateCreateInfo vi{};
        vi.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

        VkPipelineInputAssemblyStateCreateInfo ia{};
        ia.sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
        ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

        VkPipelineViewportStateCreateInfo vp{};
        vp.sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
        vp.viewportCount = 1;
        vp.scissorCount  = 1;

        VkPipelineRasterizationStateCreateInfo rs{};
        rs.sType       = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
        rs.polygonMode = VK_POLYGON_MODE_FILL;
        rs.cullMode    = VK_CULL_MODE_NONE;
        rs.frontFace   = VK_FRONT_FACE_COUNTER_CLOCKWISE;
        rs.lineWidth   = 1.0f;

        VkPipelineMultisampleStateCreateInfo ms{};
        ms.sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
        ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

        VkPipelineColorBlendAttachmentState att{};
        att.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT
                           | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

        VkPipelineColorBlendStateCreateInfo cb{};
        cb.sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
        cb.attachmentCount = 1;
        cb.pAttachments    = &att;

        VkDynamicState dyn[]{ VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
        VkPipelineDynamicStateCreateInfo dy{};
        dy.sType             = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
        dy.dynamicStateCount = 2;
        dy.pDynamicStates    = dyn;

        VkGraphicsPipelineCreateInfo gp{};
        gp.sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
        gp.stageCount          = 2;
        gp.pStages             = stages;
        gp.pVertexInputState   = &vi;
        gp.pInputAssemblyState = &ia;
        gp.pViewportState      = &vp;
        gp.pRasterizationState = &rs;
        gp.pMultisampleState   = &ms;
        gp.pColorBlendState    = &cb;
        gp.pDynamicState       = &dy;
        gp.layout              = m_pipeLayout;
        gp.renderPass          = m_renderPass;
        gp.subpass             = 0;

        return vkd.CreateGraphicsPipelines(m_dev.device, VK_NULL_HANDLE, 1, &gp, nullptr, &m_pipeline) == VK_SUCCESS;
    }

    bool SwapchainState::initFramebuffersAndDescriptors()
    {
        const auto& vkd = m_dev.vkd;
        const uint32_t n = static_cast<uint32_t>(m_realImages.size());

        m_framebuffers.resize(n, VK_NULL_HANDLE);
        for (uint32_t i = 0; i < n; ++i)
        {
            VkFramebufferCreateInfo fb{};
            fb.sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
            fb.renderPass      = m_renderPass;
            fb.attachmentCount = 1;
            fb.pAttachments    = &m_realViews[i];
            fb.width           = m_extent.width;
            fb.height          = m_extent.height;
            fb.layers          = 1;
            if (vkd.CreateFramebuffer(m_dev.device, &fb, nullptr, &m_framebuffers[i]) != VK_SUCCESS)
            { VKSUMI_LOG("CreateFramebuffer[%u] failed", i); return false; }
        }

        VkDescriptorPoolSize ps{};
        ps.type            = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        ps.descriptorCount = n;

        VkDescriptorPoolCreateInfo dpc{};
        dpc.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        dpc.maxSets       = n;
        dpc.poolSizeCount = 1;
        dpc.pPoolSizes    = &ps;
        if (vkd.CreateDescriptorPool(m_dev.device, &dpc, nullptr, &m_dsPool) != VK_SUCCESS) return false;

        std::vector<VkDescriptorSetLayout> layouts(n, m_dsLayout);
        VkDescriptorSetAllocateInfo dsa{};
        dsa.sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        dsa.descriptorPool     = m_dsPool;
        dsa.descriptorSetCount = n;
        dsa.pSetLayouts        = layouts.data();
        m_dsets.resize(n);
        if (vkd.AllocateDescriptorSets(m_dev.device, &dsa, m_dsets.data()) != VK_SUCCESS) return false;

        for (uint32_t i = 0; i < n; ++i)
        {
            VkDescriptorImageInfo dii{};
            dii.imageView   = m_fakeViews[i];
            dii.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
            dii.sampler     = m_sampler;

            VkWriteDescriptorSet w{};
            w.sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
            w.dstSet          = m_dsets[i];
            w.dstBinding      = 0;
            w.descriptorCount = 1;
            w.descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
            w.pImageInfo      = &dii;
            vkd.UpdateDescriptorSets(m_dev.device, 1, &w, 0, nullptr);
        }
        return true;
    }

    bool SwapchainState::initCommandResources()
    {
        const auto& vkd = m_dev.vkd;
        const uint32_t n = static_cast<uint32_t>(m_realImages.size());

        VkCommandPoolCreateInfo cpc{};
        cpc.sType            = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
        cpc.flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
        cpc.queueFamilyIndex = m_dev.graphicsFamily;
        if (vkd.CreateCommandPool(m_dev.device, &cpc, nullptr, &m_cmdPool) != VK_SUCCESS) return false;

        VkCommandBufferAllocateInfo ai{};
        ai.sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        ai.commandPool        = m_cmdPool;
        ai.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        ai.commandBufferCount = n;
        m_cmdBuffers.resize(n);
        return vkd.AllocateCommandBuffers(m_dev.device, &ai, m_cmdBuffers.data()) == VK_SUCCESS;
    }

    bool SwapchainState::initSemaphores()
    {
        const auto& vkd = m_dev.vkd;
        m_renderDone.resize(m_realImages.size(), VK_NULL_HANDLE);
        VkSemaphoreCreateInfo sc{};
        sc.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
        for (auto& s : m_renderDone)
            if (vkd.CreateSemaphore(m_dev.device, &sc, nullptr, &s) != VK_SUCCESS) return false;
        return true;
    }

    bool SwapchainState::initFences()
    {
        const auto& vkd = m_dev.vkd;
        m_inFlight.resize(m_realImages.size(), VK_NULL_HANDLE);
        VkFenceCreateInfo fc{};
        fc.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
        fc.flags = VK_FENCE_CREATE_SIGNALED_BIT;  // first wait passes through
        for (auto& f : m_inFlight)
            if (vkd.CreateFence(m_dev.device, &fc, nullptr, &f) != VK_SUCCESS) return false;
        return true;
    }

    std::shared_ptr<SwapchainState> SwapchainState::create(const DeviceState&              dev,
                                                           VkSwapchainKHR                  realSwapchain,
                                                           const VkSwapchainCreateInfoKHR& createInfo)
    {
        if (dev.graphicsQueue == VK_NULL_HANDLE || dev.graphicsFamily == UINT32_MAX)
        { VKSUMI_LOG("device has no graphics queue, falling back to passthrough"); return nullptr; }

        auto s = std::shared_ptr<SwapchainState>(new SwapchainState(dev, realSwapchain,
                                                                    createInfo.imageExtent,
                                                                    createInfo.imageFormat));
        if (!s->initImages(createInfo))                  return nullptr;
        if (!s->initSampler())                           return nullptr;
        if (!s->initRenderPass())                        return nullptr;
        if (!s->initDescriptorLayout())                  return nullptr;
        if (!s->initPipeline())                          return nullptr;
        if (!s->initFramebuffersAndDescriptors())        return nullptr;
        if (!s->initCommandResources())                  return nullptr;
        if (!s->initSemaphores())                        return nullptr;
        if (!s->initFences())                            return nullptr;

        VKSUMI_LOG("vksumi attached to swapchain %ux%u (format %d, %u images)",
                   createInfo.imageExtent.width, createInfo.imageExtent.height,
                   createInfo.imageFormat, (uint32_t)s->m_realImages.size());

        // we know this is an actual game window now, not some Wine helper that
        // just pokes Vulkan and never makes a swapchain. safe to drop a per-game conf
        ensurePerGameConfig();
        return s;
    }

    VkResult SwapchainState::getImages(uint32_t* pCount, VkImage* pImages)
    {
        if (!pImages)
        {
            *pCount = static_cast<uint32_t>(m_fakeImages.size());
            return VK_SUCCESS;
        }
        uint32_t n = std::min<uint32_t>(*pCount, static_cast<uint32_t>(m_fakeImages.size()));
        for (uint32_t i = 0; i < n; ++i) pImages[i] = m_fakeImages[i];
        *pCount = n;
        return n < m_fakeImages.size() ? VK_INCOMPLETE : VK_SUCCESS;
    }

    void SwapchainState::recordCommandBuffer(uint32_t i)
    {
        const auto& vkd = m_dev.vkd;
        VkCommandBuffer cb = m_cmdBuffers[i];

        vkd.ResetCommandBuffer(cb, 0);

        VkCommandBufferBeginInfo bi{};
        bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkd.BeginCommandBuffer(cb, &bi);

        // app left fake[i] in PRESENT_SRC thinking it was actually presenting,
        // flip it to something we can sample
        barrier(vkd, cb, m_fakeImages[i],
                VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,           VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                0,                                          VK_ACCESS_SHADER_READ_BIT,
                VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);

        // real image is PRESENT_SRC from last frame, or UNDEFINED if it's the
        // very first time we touch it
        barrier(vkd, cb, m_realImages[i],
                m_realFirstUse[i] ? VK_IMAGE_LAYOUT_UNDEFINED : VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
                VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                0,                                          VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
                VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,          VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT);
        m_realFirstUse[i] = false;

        VkRenderPassBeginInfo rb{};
        rb.sType             = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
        rb.renderPass        = m_renderPass;
        rb.framebuffer       = m_framebuffers[i];
        rb.renderArea.offset = { 0, 0 };
        rb.renderArea.extent = m_extent;
        vkd.CmdBeginRenderPass(cb, &rb, VK_SUBPASS_CONTENTS_INLINE);

        VkViewport vp{ 0, 0, (float)m_extent.width, (float)m_extent.height, 0, 1 };
        VkRect2D   sc{ {0,0}, m_extent };
        vkd.CmdSetViewport(cb, 0, 1, &vp);
        vkd.CmdSetScissor(cb, 0, 1, &sc);

        vkd.CmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipeline);
        vkd.CmdBindDescriptorSets(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipeLayout, 0, 1, &m_dsets[i], 0, nullptr);

        auto cfg = currentConfig();
        Knobs k = cfg->enabled ? cfg->knobs : Knobs{};
        vkd.CmdPushConstants(cb, m_pipeLayout, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(Knobs), &k);

        vkd.CmdDraw(cb, 3, 1, 0, 0);
        vkd.CmdEndRenderPass(cb);
        // render pass final layout is PRESENT_SRC so real image is good to present.
        // dont bother fixing fake's layout, app will retransition it on next acquire

        vkd.EndCommandBuffer(cb);
    }

    VkSemaphore SwapchainState::submitBlit(VkQueue            submitQueue,
                                           uint32_t           imageIndex,
                                           const VkSemaphore* waitSemaphores,
                                           uint32_t           waitCount)
    {
        const auto& vkd = m_dev.vkd;

        // hotkey: cheap XQueryKeymap each frame, on rising edge flip `enabled`
        // in a copy of the live config. editing the .conf wins over this.
        auto cfg = currentConfig();
        if (toggleKeyJustPressed(cfg->toggle_keys))
        {
            auto next = std::make_shared<Config>(*cfg);
            next->enabled = !next->enabled;
            setCurrentConfig(next);
            VKSUMI_LOG("hotkey: enabled = %s", next->enabled ? "true" : "false");
        }

        vkd.WaitForFences(m_dev.device, 1, &m_inFlight[imageIndex], VK_TRUE, UINT64_MAX);
        vkd.ResetFences  (m_dev.device, 1, &m_inFlight[imageIndex]);

        recordCommandBuffer(imageIndex);

        std::vector<VkPipelineStageFlags> waitStages(waitCount, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);

        VkSubmitInfo si{};
        si.sType                = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        si.waitSemaphoreCount   = waitCount;
        si.pWaitSemaphores      = waitCount ? waitSemaphores : nullptr;
        si.pWaitDstStageMask    = waitCount ? waitStages.data() : nullptr;
        si.commandBufferCount   = 1;
        si.pCommandBuffers      = &m_cmdBuffers[imageIndex];
        si.signalSemaphoreCount = 1;
        si.pSignalSemaphores    = &m_renderDone[imageIndex];

        VkResult sr = vkd.QueueSubmit(submitQueue, 1, &si, m_inFlight[imageIndex]);
        if (sr != VK_SUCCESS) { VKSUMI_LOG("QueueSubmit failed: %d", sr); return VK_NULL_HANDLE; }

        m_presentCount++;
        return m_renderDone[imageIndex];
    }
}
