#pragma once

#define VK_INSTANCE_FUNCS \
    FORVKFUNC(DestroyInstance) \
    FORVKFUNC(EnumerateDeviceExtensionProperties) \
    FORVKFUNC(GetInstanceProcAddr) \
    FORVKFUNC(GetPhysicalDeviceMemoryProperties) \
    FORVKFUNC(GetPhysicalDeviceQueueFamilyProperties) \
    FORVKFUNC(GetPhysicalDeviceFormatProperties)

#define VK_DEVICE_FUNCS \
    FORVKFUNC(DestroyDevice) \
    FORVKFUNC(GetDeviceProcAddr) \
    FORVKFUNC(GetDeviceQueue) \
    FORVKFUNC(QueueSubmit) \
    FORVKFUNC(QueueWaitIdle) \
    FORVKFUNC(DeviceWaitIdle) \
    FORVKFUNC(CreateSwapchainKHR) \
    FORVKFUNC(DestroySwapchainKHR) \
    FORVKFUNC(GetSwapchainImagesKHR) \
    FORVKFUNC(QueuePresentKHR) \
    FORVKFUNC(CreateImage) \
    FORVKFUNC(DestroyImage) \
    FORVKFUNC(BindImageMemory) \
    FORVKFUNC(GetImageMemoryRequirements) \
    FORVKFUNC(AllocateMemory) \
    FORVKFUNC(FreeMemory) \
    FORVKFUNC(CreateImageView) \
    FORVKFUNC(DestroyImageView) \
    FORVKFUNC(CreateSampler) \
    FORVKFUNC(DestroySampler) \
    FORVKFUNC(CreateRenderPass) \
    FORVKFUNC(DestroyRenderPass) \
    FORVKFUNC(CreateFramebuffer) \
    FORVKFUNC(DestroyFramebuffer) \
    FORVKFUNC(CreateShaderModule) \
    FORVKFUNC(DestroyShaderModule) \
    FORVKFUNC(CreateGraphicsPipelines) \
    FORVKFUNC(DestroyPipeline) \
    FORVKFUNC(CreatePipelineLayout) \
    FORVKFUNC(DestroyPipelineLayout) \
    FORVKFUNC(CreateDescriptorSetLayout) \
    FORVKFUNC(DestroyDescriptorSetLayout) \
    FORVKFUNC(CreateDescriptorPool) \
    FORVKFUNC(DestroyDescriptorPool) \
    FORVKFUNC(AllocateDescriptorSets) \
    FORVKFUNC(UpdateDescriptorSets) \
    FORVKFUNC(CreateCommandPool) \
    FORVKFUNC(DestroyCommandPool) \
    FORVKFUNC(AllocateCommandBuffers) \
    FORVKFUNC(FreeCommandBuffers) \
    FORVKFUNC(ResetCommandBuffer) \
    FORVKFUNC(BeginCommandBuffer) \
    FORVKFUNC(EndCommandBuffer) \
    FORVKFUNC(CmdBeginRenderPass) \
    FORVKFUNC(CmdEndRenderPass) \
    FORVKFUNC(CmdBindPipeline) \
    FORVKFUNC(CmdBindDescriptorSets) \
    FORVKFUNC(CmdPushConstants) \
    FORVKFUNC(CmdSetViewport) \
    FORVKFUNC(CmdSetScissor) \
    FORVKFUNC(CmdDraw) \
    FORVKFUNC(CmdPipelineBarrier) \
    FORVKFUNC(CreateSemaphore) \
    FORVKFUNC(DestroySemaphore) \
    FORVKFUNC(CreateFence) \
    FORVKFUNC(DestroyFence) \
    FORVKFUNC(WaitForFences) \
    FORVKFUNC(ResetFences)
